//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archimind.Platform.DataModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Archimind.Platform.DataModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application error with id {handlingInstanceID} occurred and has been logged. Please contact your administrator..
        /// </summary>
        internal static string RES_DataLayerExceptionHandlerMessage {
            get {
                return ResourceManager.GetString("RES_DataLayerExceptionHandlerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception type {0] is not of type Exception..
        /// </summary>
        internal static string RES_DataLayerInvalidExceptionType {
            get {
                return ResourceManager.GetString("RES_DataLayerInvalidExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in the Data Model Layer..
        /// </summary>
        internal static string RES_DataModelError {
            get {
                return ResourceManager.GetString("RES_DataModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing a repository operation. The repository command wasn&apos;t properly initialized..
        /// </summary>
        internal static string RES_RepositoryCommandNotInitialized {
            get {
                return ResourceManager.GetString("RES_RepositoryCommandNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing a repository operation. The repository connection wasn&apos;t properly initialized..
        /// </summary>
        internal static string RES_RepositoryConnectionNotInitialized {
            get {
                return ResourceManager.GetString("RES_RepositoryConnectionNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing a repository operation..
        /// </summary>
        internal static string RES_RepositoryError {
            get {
                return ResourceManager.GetString("RES_RepositoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing a repository operation. The repository wasn&apos;t properly initialized..
        /// </summary>
        internal static string RES_RepositoryNotInitialized {
            get {
                return ResourceManager.GetString("RES_RepositoryNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing a repository operation. The repository transaction wasn&apos;t properly initialized..
        /// </summary>
        internal static string RES_RepositoryTransactionNotInitialized {
            get {
                return ResourceManager.GetString("RES_RepositoryTransactionNotInitialized", resourceCulture);
            }
        }
    }
}
